# Generated by Django 4.2.7 on 2023-11-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='company')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('street_address', models.CharField(blank=True, max_length=200, verbose_name='street address')),
                ('locality', models.CharField(blank=True, max_length=50, verbose_name='locality')),
                ('province', models.CharField(blank=True, choices=[('DSL', 'Dolnośląskie'), ('K-P', 'Kujawsko-pomorskie'), ('LBL', 'Lubelskie'), ('LBU', 'Lubuskie'), ('LDZ', 'Łódzkie'), ('MAZ', 'Mazowieckie'), ('MLP', 'Małopolskie'), ('OPO', 'Opolskie'), ('PDL', 'Podlaskie'), ('PKR', 'Podkarpackie'), ('POM', 'Pomorskie'), ('SL', 'Śląskie'), ('SW', 'Świętokrzyskie'), ('WLP', 'Wielkopolskie'), ('W-M', 'Warmińsko-mazurskie'), ('ZPM', 'Zachodniopomorskie')], max_length=3, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='postal_code')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
            ],
        ),
    ]
